#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-configparser
Version  : 5.2.0
Release  : 5
URL      : https://files.pythonhosted.org/packages/02/a8/5fae273a45a3e4e34ea560c99a4843fe2d9fc6fb691de064dc9c72c46e57/configparser-5.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/02/a8/5fae273a45a3e4e34ea560c99a4843fe2d9fc6fb691de064dc9c72c46e57/configparser-5.2.0.tar.gz
Summary  : Updated configparser from Python 3.8 for Python 2.6+.
Group    : Development/Tools
License  : MIT
Requires: pypi-configparser-license = %{version}-%{release}
Requires: pypi-configparser-python = %{version}-%{release}
Requires: pypi-configparser-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
.. image:: https://img.shields.io/pypi/v/configparser.svg
:target: `PyPI link`_
.. image:: https://img.shields.io/pypi/pyversions/configparser.svg
:target: `PyPI link`_

%package license
Summary: license components for the pypi-configparser package.
Group: Default

%description license
license components for the pypi-configparser package.


%package python
Summary: python components for the pypi-configparser package.
Group: Default
Requires: pypi-configparser-python3 = %{version}-%{release}

%description python
python components for the pypi-configparser package.


%package python3
Summary: python3 components for the pypi-configparser package.
Group: Default
Requires: python3-core
Provides: pypi(configparser)

%description python3
python3 components for the pypi-configparser package.


%prep
%setup -q -n configparser-5.2.0
cd %{_builddir}/configparser-5.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649730780
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-configparser
cp %{_builddir}/configparser-5.2.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-configparser/8e6689d37f82d5617b7f7f7232c94024d41066d1
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-configparser/8e6689d37f82d5617b7f7f7232c94024d41066d1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
